### ISSUE TITLE
break when call to NtTestAlert with no args

### ISSUE THREAD

**Issue by timwhitez** [C-Sto/BananaPhone#10]
break when call to NtTestAlert with no args

**Comment by C-Sto** [comment]
Please check out https://github.com/C-Sto/BananaPhone/tree/sneakysys - this branch includes syscall instruction borrowing, and should also fix the no-args case.

**Comment by timwhitez** [comment]
good job!

**Comment by timwhitez** [comment]
am i right to fix raw bananaphone like this?

TEXT ·bpSyscall(SB), $0-56
	XORQ AX,AX
	MOVW callid+0(FP), AX
	PUSHQ CX
	//put variadic size into CX
	MOVQ argh_len+16(FP),CX
	//put variadic pointer into SI
	MOVQ argh_base+8(FP),SI
	// SetLastError(0).
	MOVQ	0x30(GS), DI
	MOVL	$0, 0x68(DI)
	SUBQ	$(maxargs*8), SP	// room for args
	//no parameters, special case
	CMPL CX, $0
	JLE callz
	// Fast version, do not store args on the stack.
	CMPL	CX, $4
	JLE	loadregs
	// Check we have enough room for args.
	CMPL	CX, $maxargs
	JLE	2(PC)
	INT	$3			// not enough room -> crash
	// Copy args to the stack.
	MOVQ	SP, DI
	CLD
	REP; MOVSQ
	MOVQ	SP, SI
loadregs:
	//move the stack pointer????? why????
	SUBQ	$8, SP
	// Load first 4 args into correspondent registers.
	MOVQ	0(SI), CX
	MOVQ	8(SI), DX
	MOVQ	16(SI), R8
	MOVQ	24(SI), R9
	// Floating point arguments are passed in the XMM
	// registers. Set them here in case any of the arguments
	// are floating point values. For details see
	//	https://msdn.microsoft.com/en-us/library/zthk2dkh.aspx
	MOVQ	CX, X0
	MOVQ	DX, X1
	MOVQ	R8, X2
	MOVQ	R9, X3
	//MOVW callid+0(FP), AX
	MOVQ CX, R10
	SYSCALL
	ADDQ	$((maxargs+1)*8), SP
	// Return result.
	POPQ	CX
	MOVL	AX, errcode+32(FP)
	RET
	PUSHQ CX
callz:
	MOVQ CX, R10
	SYSCALL
	ADDQ	$((maxargs)*8), SP
	// Return result.
	POPQ	CX
	MOVL	AX, errcode+32(FP)
	RET

**Comment by C-Sto** [comment]
that should work. With a bit more testing on sneakysys I'll merge it into master, but that snippet should do for now (though you may have an error with unbalanced push/pop)

**Comment by timwhitez** [comment]
in my test 
SUBQ $8, SP
is unnecessary on sneakysys
it will impact the param
